// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWjxpKUxuZaSkI9hgOEk8Kz8dhPR7GkQ',
    appId: '1:662302739897:web:9e2528daf5273627f3ba68',
    messagingSenderId: '662302739897',
    projectId: 'proyectoequipo3-75954',
    authDomain: 'proyectoequipo3-75954.firebaseapp.com',
    storageBucket: 'proyectoequipo3-75954.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-L9QwBBolMGdI0_XNMQgGdwuyJrNFQU',
    appId: '1:662302739897:android:23baec9fb9d83cacf3ba68',
    messagingSenderId: '662302739897',
    projectId: 'proyectoequipo3-75954',
    storageBucket: 'proyectoequipo3-75954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQLfwTUMBbIzYu1JQnbDIEmzYEN95ARLo',
    appId: '1:662302739897:ios:2cf00ebc663df6b4f3ba68',
    messagingSenderId: '662302739897',
    projectId: 'proyectoequipo3-75954',
    storageBucket: 'proyectoequipo3-75954.appspot.com',
    iosBundleId: 'com.example.flutterProyectoEquipo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQLfwTUMBbIzYu1JQnbDIEmzYEN95ARLo',
    appId: '1:662302739897:ios:e68ba40194763d4ef3ba68',
    messagingSenderId: '662302739897',
    projectId: 'proyectoequipo3-75954',
    storageBucket: 'proyectoequipo3-75954.appspot.com',
    iosBundleId: 'com.example.flutterProyectoEquipo3.RunnerTests',
  );
}
